enabled: true

buildDeps:
  - hs-build-tools

steps:
  - description: Build maven archive for or-tools
    commands:
      - cmake -S. -Bbuild -DBUILD_JAVA=ON
      - cmake --build build --target java_package -v
