enabled: true

buildDeps:
  - hs-build-tools

steps:
  - description: Enable debug
    commands:
      - echo "set -e" >> $BUILD_COMMAND_RC_FILE
  - description: Build maven archive for or-tools
    commands:
      - make archive_java
